### ISSUE TITLE
Cannot create S3 bucket in us-east-1 region

### ISSUE THREAD

**Issue by mumumumu** [Qovery/Replibyte#104]
I've noticed I'm not able to initialize an S3 bucket in the `us-east-1` region.

My `replibyte.yaml`:
```yml
datastore:
  aws:
    bucket: $S3_BUCKET
    region: $S3_REGION
    access_key_id: $S3_ACCESS_KEY_ID
    secret_access_key: $S3_SECRET_ACCESS_KEY
```

Running `replibyte -c replibyte.yaml dump list` with `S3_BUCKET=us-east-1` results in this error:
```sh
[2022-05-14T03:13:11Z ERROR replibyte::datastore::s3] Error { code: "InvalidLocationConstraint", message: "The specified location-constraint is not valid", request_id: "...", s3_extended_request_id: "..." }
failed to create bucket 'replibyte'
```
But the command works fine with `S3_BUCKET=us-east-2` and creates the bucket as expected.

I've attempted a workaround (https://github.com/mumumumu/replibyte/commit/c6eff63c5adb81756ab17dd28a05e074fc27e8ff), and it works, but I'm not sure if there's a better way to handle this (I'm not really a rust dev 😅).
