### ISSUE TITLE
mongo dump not working, terminal without output

### ISSUE THREAD

**Issue by victorgomezg93** [Qovery/Replibyte#125]
Hi, and thank you really much for your efforts. I'm trying to make an anonymous dump using replibyte and a mongo database but I think is not working as expected. I have my conf.yaml, really simple just to avoid interactions and I'm doing everything locally to avoid mistakes.

**conf.yaml**
```
source:
  connection_uri: mongodb://mongo:mongo@localhost:27017/test
  transformers: # optional - hide sensitive data
      - database: test
        table: employees
        columns:
          - name: surname
            transformer_name: random
          - name: first_name
            transformer_name: first-name
          - name: email
            transformer_name: email
          - name: phone_ext
            transformer_name: phone-number
destination:
  connection_uri: mongodb://mongo:mongo@localhost:27017/test # you can use $DATABASE_URL
datastore:
  local_disk:
    dir: .
```

But everytime I run `replibyte -c conf.yaml dump create ` I have no answer in the terminal, sometimes I can see this message "No such file or directory (os error 2)". I'm using mongo4.4 is not supported?

![image](https://user-images.githubusercontent.com/45047366/169276093-1e4fac41-3a25-441a-939e-c977d2b4aba1.png)

I just want to run the transformer but I'm not sure if I can. Thank you very much for your help.

Kind regards
