### ISSUE TITLE
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value'

### ISSUE THREAD

**Issue by marigbede** [Qovery/Replibyte#134]
It seems that replibyte is having some issues with **None** values in the database. Is there a workaround for this?

`thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', replibyte/src/source/postgres.rs:288:48
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::panicking::panic
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:48:5
   3: replibyte::source::postgres::transform_columns
   4: replibyte::source::postgres::read_and_transform::{{closure}}
   5: dump_parser::utils::list_sql_queries_from_dump_reader
   6: <replibyte::source::postgres::Postgres as replibyte::source::Source>::read
   7: <replibyte::tasks::full_dump::FullDumpTask<S> as replibyte::tasks::Task>::run
   8: replibyte::commands::dump::run
   9: replibyte::main`

My yaml is below. Please note that **REDACTED** replaced actual values.
`
source:
  connection_uri: REDACTED
  transformers:
    - database: public
      table: users
      columns:
      - name: full_name
        transformer_name: random
datastore:
  gcp:
    bucket: REDACTED
    region: us-west1
    access_key: REDACTED
    secret: REDACTED
destination:
  connection_uri: REDACTED
`

The command is 
`./replibyte -c /local/replibyte_config.yaml dump create`

**Comment by evoxmusic** [comment]
Hi @marigbede , thanks for the report. Can you reformat your yaml conf file?

**Comment by marigbede** [comment]
@evoxmusic Thanks for picking this up. Please see this attached file. 

[replibyte.txt](https://github.com/Qovery/Replibyte/files/8771968/replibyte.txt)

**Comment by evoxmusic** [comment]
Thx, here is the content 

```yaml
source:
  connection_uri: REDACTED
  transformers:
    - database: public
      table: users
      columns:
      - name: full_name
        transformer_name: random
datastore:
  gcp:
    bucket: REDACTED
    region: us-west1
    access_key: REDACTED
    secret: REDACTED
destination:
  connection_uri: REDACTED
```

**Comment by marigbede** [comment]
@evoxmusic  its looking as if the code crashes when NONE is encountered in the database. Is this the same experience you have?

**Comment by marigbede** [comment]
So @evoxmusic I have bene able to trace this back here https://github.com/Qovery/Replibyte/blob/a8c56df6e1277e7eadf0806105de995c7fd4d809/replibyte/src/source/postgres.rs#L289. 

From the tests that I performed showed that even without the transforms config, the issue still occurs.

**Comment by spatail** [comment]
I am running in to the same error when attempting to dump data from Postgres to S3 with no transformers.

My config file:
```
source:
  connection_uri: postgres://[redacted]
datastore:
  aws:
    bucket: [redacted]
    region: [redacted]
    credentials:
      access_key_id: [redacted]
      secret_access_key: [redacted]
```

I am starting Replibyte using Docker:
`docker run -it --rm -v "$(pwd)/replibyte.yaml:/replibyte.yaml:ro" replibyte -n --config replibyte.yaml dump create`

The stacktrace:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', replibyte/src/source/postgres.rs:289:48
0: rust_begin_unwind
             at ./rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at ./rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::panicking::panic
             at ./rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:48:5
   3: replibyte::source::postgres::transform_columns
   4: replibyte::source::postgres::read_and_transform::{{closure}}
   5: dump_parser::utils::list_sql_queries_from_dump_reader
   6: <replibyte::source::postgres::Postgres as replibyte::source::Source>::read
   7: <replibyte::tasks::full_dump::FullDumpTask<S> as replibyte::tasks::Task>::run
   8: replibyte::commands::dump::run
   9: replibyte::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
