### ISSUE TITLE
Feature: add options to dump specific tables

### ISSUE THREAD

**Issue by fabriceclementz** [Qovery/Replibyte#150]
As we discussed on Discord, it will be great to have some options to dump specific tables.
By adding a new option `only_tables` RepliByte will only dump these tables.

This is an example of the final config file:

```yaml
source:
  only_tables:
    - database: public
      table: us_states
    - database: public
      table: order_details
```

Here only the tables named `us_states` and `order_details` must be included in the dump.

An error must be triggered if a table is present  in `skip` and `only_tables` when both options are used in conjunction.
