### ISSUE TITLE
Unexpected EOF while in a multi-line comment

### ISSUE THREAD

**Issue by ronzyfonzy** [Qovery/Replibyte#170]
I tried Replibyte today and got to an issue. When creating a dump I get the following error
```bash
ubuntu@flex-dev-01:~/tools/replibyte$ replibyte -c config-develop.yml dump create
⠖ [00:00:00] [>-----------------------------------------------------------------------------------------------------------------------------------------------------] 2.71KiB/100.00MiB (46m)
failing query: '
/*!50003 CREATE*/ /*!50017 DEFINER=`flex_xxx`@`%`*/ /*!50003 TRIGGER `addon_items_AI` AFTER INSERT ON `addon_items` FOR EACH ROW BEGIN
    IF @MIGRATION IS NULL
    THEN

'
thread 'main' panicked at 'TokenizerError { message: "Unexpected EOF while in a multi-line comment", line: 2, col: 5 }', dump-parser/src/mysql/mod.rs:708:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The config file
```yml
source:
  connection_uri: mysql://flex_xxx:xxxxx@xxx.com:3306/develop
  database_subset:
    database: public
    table: in_receivements
    strategy_name: random
    strategy_options:
      percent: 0
datastore:
  local_disk:
    dir: /home/ubuntu/tools/replibyte/data
destination:
  connection_uri: mysql://flex_yyy:yyy@yyy:3306/develop
```
