### ISSUE TITLE
Transformers don't work with tables containing uppercase letters

### ISSUE THREAD

**Issue by mkgharbi** [Qovery/Replibyte#174]
Hi
 
Transformers are not working correctly with tables containing uppercase characters (in my case a table named **User**). 
When I renamed the table to **user**, it worked perfectly. 
Is there a solution to make uppercase table names work on transformers ?

The conf.yaml file I used is: 
```yaml
source:
  connection_uri: $DATABASE_SOURCE_URL
  transformers:
    - database: public
      table: User
      columns:
        - name: name
          transformer_name: random
        - name: email
          transformer_name: email
datastore:
  aws:
    bucket: $BUCKET_NAME
    region: $S3_REGION
    credentials:
      access_key_id: $ACCESS_KEY_ID
      secret_access_key: $AWS_SECRET_ACCESS_KEY
destination:
  connection_uri: $DATABASE_DESTINATION_URL
```

**Comment by evoxmusic** [comment]
Can you give more details on which database do you use?

**Comment by karpa4o4** [comment]
Hi @evoxmusic. I have tested and this problem is only in PostgreSQL. This is because PostgreSQL requires wrap table names in quotes if they contain uppercase characters.
A simple solution to the problem is to wrap the table name in quotes (as in the screenshot), in which case I can reflect this behavior in the documentation.
![Screenshot_20220716_210613](https://user-images.githubusercontent.com/33448939/179367013-bb7fbf86-d239-47e3-b157-ae9332006f2a.png)

**Comment by karpa4o4** [comment]
A more complex solution is to implement automatic quotes when creating a dump for PostgreSQL.

**Comment by nilscam** [comment]
Hi, it looks like columns name have the same issue :

The following doesn't work :
```
transformers:
    - database: public
       table: User
       columns:
          - name: pictureUrl
          ...
```

But the following works :
```
transformers:
    - database: public
       table: User
       columns:
          - name: '"pictureUrl"'
          ...
```
