### ISSUE TITLE
Feature: skip table synchronization

### ISSUE THREAD

**Issue by evoxmusic** [Qovery/replibyte#18]
Hi, a user asked me if it was possible to skip one or more tables from the synchronization. The use case was: some tables are pretty heavy (> 100GB) and do not need to be synchronized for a development environment. 

To skip the `public.logs` table, the configuration YAML could be like this:

```
source:
  connection_uri: postgres://root:password@localhost:5432/root
  skip:
    - database: public
      table: logs
  transformers:
    - database: public
      table: employees
      columns:
        - name: fist_name
          transformer: first-name
        - name: last_name
          transformer: random
bridge:
  bucket: replibyte-test
  region: us-east-2
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
```

Feel free to pick this issue.
