### ISSUE TITLE
Creating dump for MySQL database is very slow with 

### ISSUE THREAD

**Issue by nik-lampe** [Qovery/Replibyte#189]
I've ran into an issue while creating a dump of my mysql database. The dump command runs for such a long time that at some point I cancelled it. Don't know if it ever finishes.

I tried to hunt down the problem and came up with a minimum reproducable mysqldump of one table with 5 columns and ~3500 Rows. The dump size is 219kb. As soon as I remove another column (doesn't even matter which one), the dump is done within seconds.

I can't really pin down the issue. When I remove the entries with the "ß" character it's also done in seconds. But when I remove every row except the ones with the "ß" it works too. 😅 

I have attached the dumpfile (renamed to .txt so github accepts it)

My config is simple:
```
source:
  connection_uri: mysql://user:password@localhost/database
datastore:
  local_disk:
    dir: ./data
```

[slow-replibyte.sql.txt](https://github.com/Qovery/Replibyte/files/9113767/slow-replibyte.sql.txt)
