### ISSUE TITLE
Replibyte appears "stuck" during export from Postgres

### ISSUE THREAD

**Issue by zovt** [Qovery/Replibyte#200]
Repost of my [Discord message](https://discord.com/channels/688766934917185556/952516115039408168/999727830898311260)

Hey all. We're trying to use `replibyte` to scrub some data, but unfortunately it appears to be getting stuck (for lack of a better word). I've run it under `strace`, and it looks like there are a bunch of read syscalls going on up until the point where it gets stuck. Happy to provide any other information that would be helpful to debugging this! 

We're running version 0.9.3, dumping from a postgres database and trying to upload to S3 for context.

Also, the CPU is pinned to max and the memory usage is constant after the point where it gets stuck

**Comment by evoxmusic** [comment]
Hi @zovt , thank you for reporting this issue. Do you have a dump with your syscalls? Can you provide me your replibyte config yaml to see which options you use? Thank you.

**Comment by zovt** [comment]
config:
```
source:
  connection_uri: <snip>
  transformers:
    - database: <snip>
      table: <snip>
      columns:
        - name: email
          transformer_name: email
        - name: phone_number
          transformer_name: phone-number
        - name: <snip>
          transformer_name: random
    - database: <snip>
      table: <snip>
      columns:
        - name: email
          transformer_name: email
        - name: phone_number
          transformer_name: phone-number
datastore:
  aws:
    bucket: <snip>
    region: <snip>
    credentials:
      secret_access_key: <snip>
      access_key_id: <snip>
 ```

[syscalls.log](https://github.com/Qovery/Replibyte/files/9162851/syscalls.log)

I've snipped out the strings from the `read` calls, but the big block at the bottom look like data from a psql dump.

I invoked replibyte like this: `strace -o syscalls.log replibyte -c replibyte.conf dump create`
