### ISSUE TITLE
Issues with documentation

### ISSUE THREAD

**Issue by jeromewaibel** [Qovery/Replibyte#202]
replibyte 0.9.5

---

https://www.replibyte.com/docs/guides/restore-a-dump says

replibyte -c conf.yaml dump restore local -d postgresql -v latest
-d parameter accepts mongodb, mysql and other databases supported by Replibyte.

while the parameter is -i / --image

---

https://www.replibyte.com/docs/getting-started/configuration says as an example

```
datastore:
  aws:
    bucket: $BUCKET_NAME
    region: $S3_REGION
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
```

though it is

```
datastore:
  aws:
    bucket: $BUCKET_NAME
    region: $S3_REGION
    credentials:
       access_key_id: $ACCESS_KEY_ID
       secret_access_key: $AWS_SECRET_ACCESS_KEY
```
