### ISSUE TITLE
upload to s3 performance issues

### ISSUE THREAD

**Issue by DoctorOgg** [Qovery/replibyte#215]
Trying to upload a 100G Postgres dump from an ec2 instance running in the same region as the bucket, the speed seems to be a bit slow. Using the AWS CLI I was able to upload the raw dump to the bucket in about 15Min. However, Replibye is now on its 2nd day running. Any ideas to speed up the process.

My config:

```yaml
source:
  connection_uri: stdin
datastore:
  aws:
    bucket: REDACTED
    region: us-west-2
    credentials:
      access_key_id: REDACTED
      secret_access_key: REDACTED

```
