### ISSUE TITLE
TokenizerError: Unexpected EOF while in a multi-line comment

### ISSUE THREAD

**Issue by vinifmor** [Qovery/Replibyte#243]
Hi there,

I was trying to generate a dump from a MariaDB instance, but got the following error:
`thread 'main' panicked at 'TokenizerError { message: "Unexpected EOF while in a multi-line comment", line: 2, col: 5 }', dump-parser/src/mysql/mod.rs:760:13`

Full logs [here](https://github.com/Qovery/Replibyte/files/10176326/replibyte.txt)

My configuration file looks like:
```
source:
  connection_uri: mysql://db:pwd@127.0.0.1:3306/db
  transformers:
  - database: suitecrm
    table: users
    columns:
      - name: description
        transformer_name: random
      - name: first_name
        transformer_name: first-name
  database_subset:
    database: db
    table: test
    strategy_name: random
    strategy_options:
      percent: 5
datastore:
  local_disk:
    dir: ./datastore
destination:
  connection_uri: mysql://db:pwd@127.0.0.1:3307/db
```

The source and destination databases are two containers from the official MariaDB image from Dockerhub (`mariadb:10`)

I've executed the `dump create` command from within a Docker container of the official **replibyte** image.

Do you what could be wrong on my setup ? or is there any possible workaround ?
