### ISSUE TITLE
Running replibyte results in command being killed 

### ISSUE THREAD

**Issue by pKorsholm** [Qovery/Replibyte#244]
I'm currently running replibyte trying to subset my database. 

My config is something like: 
```
source:
  connection_uri: $DB_URL
  database_subset:
    database: public
    table: cart
    strategy_name: random
    strategy_options:
      percent: 20
    passthrough_tables: 
      - country
      .... 
      <30 more tables> 
  transformers: 
    - database: public
      table: customer
      columns:
        - name: email
          transformer_name: email
    ... 
    <23 columns and 8 tables>    
```

This results in replibyte running out of memory (I'm guessing given the screenshot of the process from my activity montitor below, taken right before the process crashed)

<img width="639" alt="image" src="https://user-images.githubusercontent.com/88927411/206724624-19b41d51-a26b-4e18-9741-f1780601cff3.png">

Is there any way to reduce the memory consumption, the database is in total around 250mb (148mb if asking postgres with: `SELECT pg_size_pretty( pg_database_size('dbname') )`) and 51gb of memory taken up seems excessive.
