### ISSUE TITLE
Not working --file option?

### ISSUE THREAD

**Issue by ishikawa-pro** [Qovery/Replibyte#245]
Hi there.
I tried to create a dump using MongoDB's manual dump file with reference to this doc.
https://www.replibyte.com/docs/guides/create-a-dump#option-2-make-a-dump-manually

this command is working.
```
cat sample_dump | replibyte -c config.yaml dump create -s mongodb -i
```

but this command infinitely spins a spinner and don't complete.
```
replibyte -c config.yaml dump create -s mongodb -i --file sample_dump
```

I checked the code and it seems to stop at this line.
https://github.com/Qovery/Replibyte/blob/d6b35a7455b7b9d6bc1456b3fe1f7644377e7153/replibyte/src/commands/dump.rs#L200

I guess it occurs other than MongoDB, and #209 is related to this issue.
I want to try fixing this bug but I don't know how to fix it.

### Environment
OS:  Mac OS Monterey (12.5)
System Model Name: Macbook Pro
CPU: Apple M1 Max
replibyte version: 0.10.0
config: 
```yaml
source:
  connection_uri:
    mongodb://root:password@localhost:27017/
destination:
  connection_uri:
    mongodb://root:password@localhost:27017/
datastore:
  local_disk:
    dir: /datastore
```
