### ISSUE TITLE
multiple database name locations in configuration

### ISSUE THREAD

**Issue by janrito** [Qovery/Replibyte#248]
The connection URI includes the database name—but transformers and subsets also ask for a database parameter? does one override the other?

```yaml
connection_uri: postgres://user:password@host:port/db
  transformers:
    - database: public
      table: customers
      ....
  database_subset:
    database: public
    table: customers
```

is the database public? db? can we leave one out?
