### ISSUE TITLE
Ignore tables

### ISSUE THREAD

**Issue by janrito** [Qovery/Replibyte#250]
Transformers are great for some use-cases, but it would be nice to be able to just ignore the data in some tables.
For example, auth tokens

**Comment by xMunch** [comment]
There does seem to be a skip options you can apply for this

```
source:
  connection_uri: $DATABASE_URL
  skip:
    - database: public
      table: auth_tokens
```
