### ISSUE TITLE
Why not allow multiple tables in database_subset?

### ISSUE THREAD

**Issue by koolay** [Qovery/Replibyte#261]
```yaml
database_subset:
    database: abc
    table: tab1
    strategy_name: random
    strategy_options:
      percent: 1

```
The database_subset.table is only allow one value.
