### ISSUE TITLE
Very slow performance (~2MB/s), process eventually killed

### ISSUE THREAD

**Issue by samcfinan** [Qovery/replibyte#264]
Hi there,

I'm using 0.10.0 with the following config:

```
# encryption_key: $MY_PRIVATE_ENC_KEY # optional - encrypt data on datastore
source:
  connection_uri: postgres://XXXX:XXXX@0.0.0.0:5432/XXXX # you can use $DATABASE_URL
datastore:
  gcp:
    bucket: XXXX
    region: us-east1
    access_key: XXXX
    secret: XXXX
destination:
  connection_uri: postgres://XXXX:XXXX@0.0.0.0:3000/XXXX # you can use $DATABASE_URL
```
The source database is remote, the destination database is running locally in Docker.

The database is approximately 15GB on disk and is running at < 5% CPU utilization. It's a remote database hosted on GCP Cloud SQL. I've observed network activity below 2MB/s while running replibyte. Eventually, the process is killed

```
[1]    28147 killed     replibyte -c replibyte.conf.yaml dump create
```
