### ISSUE TITLE
Import dump are real data

### ISSUE THREAD

**Issue by Nicolas-Her** [Qovery/Replibyte#269]
Hi,

i try to anonymize data on dump but when i restore it on my dev environnement i have real data

do i miss something ?

```
source:
  connection_uri: $DATABASE_URL
  transformers:
    - database:  ****
      table:  ****
      columns:
        - name: name
          transformer_name: first-name
        - name: email
          transformer_name: custom-wasm
          transformer_options:
            path: ****
        - name: photo_path
          transformer_name: custom-wasm
          transformer_options:
            path:  ****
        - name: remember_token
          transformer_name: random
        - name: guest_email
          transformer_name: email
    - database:  ****
      table:  ****
      columns:
        - name: floor_plan_path
          transformer_name: custom-wasm
          transformer_options:
            path:  ****
    - database:  ****
      table:  ****
      columns:
        - name: value
          transformer_name: custom-wasm
          transformer_options:
            path:  ****
    - database:  ****
      table:  ****
      columns:
        - name: value
          transformer_name: custom-wasm
          transformer_options:
            path:  ****
```
