### ISSUE TITLE
[Question] Can we pass options to a custom-wasm transformer?

### ISSUE THREAD

**Issue by gido** [Qovery/Replibyte#272]
I would like to implement a custom transformer that implement something described in #115:

The configuration could be something like:

```yaml
# ...
   - database: <your-db-name>
     table: <your-table-name>
     columns:
       - name: <your-column-name>
         transformer_name: custom-wasm
         transformer_options:
           path: "path/to/your/hardcoded-value-wasm-transformer.wasm"
           value: "MY CUSTOM VALUE"
# ...
```

Is this currently possible to pass some options to my custom transformer?
