### ISSUE TITLE
Possible to skip whole schemas 

### ISSUE THREAD

**Issue by louiscb** [Qovery/replibyte#305]
Is it possible to skip whole schemas? E.g 

```
source:
  connection_uri: postgres://root:password@localhost:5432/root
  skip:
    - schema: reports
```
