### ISSUE TITLE
Dump create yields old data

### ISSUE THREAD

**Issue by Dufran** [Qovery/replibyte#306]
Hi all, i was using replibyte as backup/remote restore tool for over a week, and all was working OK.
Last Friday dump create start creating not complete dump (not all folders have data)
replibyte.yaml

```
source:
  connection_uri: $SOURCE_DB_URL
datastore:
  local_disk:
      dir: $BACKUP_FOLDER
destination:
  connection_uri: $TARGET_DB_URL
```
taskfile with commands
```
  restore.remote:
    cmds:
      - replibyte -c replibyte.yaml dump restore remote -v latest
  dump.create:
    cmds:
      - replibyte -c replibyte.yaml dump create
  dump.clean:
    cmds:
      - replibyte -c replibyte.yaml dump delete --older-than 1d
```
So i run 
dump.create && restore.remote && dump.clean

And this previously was resulting in correct data on remote database

I have a postgresql binary and replibyte installed on source host
