### ISSUE TITLE
Backup is encrypted while no encryption is set

### ISSUE THREAD

**Issue by evoxmusic** [Qovery/replibyte#53]
Everything is in the title :) 

```shell
~/I/q/replibyte (main|…) $ replibyte -c qovery-replibyte.yaml backup list
⠤
 name                 | size  | when           | compressed | encrypted
----------------------+-------+----------------+------------+-----------
 backup-1650796765697 | 87 kB | 42 minutes ago | true       | false
 backup-1650794871640 | 35 kB | 1 hour ago     | true       | false
 backup-1650789943393 | 44 kB | 3 hours ago    | true       | false
 backup-1650789414794 | 3 kB  | 3 hours ago    | true       | false
 backup-1650788239683 | 33 kB | 3 hours ago    | true       | false
```

the conf file

```yaml
source:
  connection_uri: postgres://root:password@localhost:5432/root
bridge:
  bucket: replibyte-qovery-7
  region: us-east-2
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
```

here is a screenshot of the encrypted data

![image](https://user-images.githubusercontent.com/1284743/164975430-34cadf6d-ca9d-4584-9302-56b0e5cbb327.png)

---
This is probably a bug in the CLI arg parsing
