### ISSUE TITLE
Feature: implement database subseting for MongoDB

### ISSUE THREAD

**Issue by evoxmusic** [Qovery/replibyte#70]
Implement database subsetting for MongoDB as [we did for PostgreSQL.](https://github.com/Qovery/replibyte/issues/40).

However, MongoDB is not a relational database and we need to support "Virtual Foreign Key". Meaning, as a user I want to indicate that `column collection_a.post_id` is linked to `column collection_b.id` and then keep the consistency across the collections.

**Comment by benny-n** [comment]
> Meaning, as a user I want to indicate that column collection_a.post_id is linked to column collection_b.id

How would you indicate that as a user?
If there isn't a known standard in MongoDB for such behavior, I'm not really sure how we can add support for this concept.

**Comment by evoxmusic** [comment]
From my experience, developers using MongoDB (and any NoSQL db) end up managing relations between collections (MongoDB table concept) from their code. We can add a way to declare virtual relations between tables in the YAML file. Eg.

```yaml
source:
  connection_uri: postgres://root:password@localhost:5432/root
  database_subset:
    database: public
    virtual_relations:
      - from_table: collection_a
         from_column: post_id
      - to_table: collection_b
         to_column: id
    table: orders
    strategy_name: random
    strategy_options:
      percent: 50
    passthrough_tables:
      - us_states
```

WDYT?
