### ISSUE TITLE
New subset strategy: create SELECT with WHERE clause strategy

### ISSUE THREAD

**Issue by evoxmusic** [Qovery/replibyte#74]
As a user, I want to select a subset of a database based on a SELECT and WHERE clause. 

```yaml
source:
  database_subset:
    database: public
    table: orders
    strategy_name: query
    strategy_options:
      query: "SELECT * FROM public.table WHERE customer_id = 'abcdef' AND total_cost_usd > 50"
```

It means that we need to create a small SQL parser to build a conditional tree and filter on those conditions. 

Examples of queries we can support:

- `SELECT * FROM public.table WHERE customer_id = 'abcdef';`
- `SELECT * FROM public.table WHERE customer_id = 'abcdef' AND total_cost_usd > 50;`
- `SELECT * FROM public.table WHERE customer_id = 'abcdef' AND total_cost_usd < 50;`
- `SELECT * FROM public.table WHERE customer_id = 'abcdef' AND total_cost_usd <= 50;`
- `SELECT * FROM public.table WHERE customer_id = 'abcdef' AND total_cost_usd >= 50;`
- `SELECT * FROM public.table WHERE customer_id = 'abcdef' AND total_cost_usd != 50;`
- `SELECT * FROM public.table WHERE customer_id = 'abcdef' OR total_cost_usd > 50;`
- `SELECT * FROM public.table WHERE customer_id = 'abcdef' OR total_cost_usd < 50;`
- `SELECT * FROM public.table WHERE customer_id = 'abcdef' OR total_cost_usd <= 50;`
- `SELECT * FROM public.table WHERE customer_id = 'abcdef' OR total_cost_usd >= 50;`
- `SELECT * FROM public.table WHERE customer_id = 'abcdef' OR total_cost_usd != 50;`

---

As an improvement, we can put `database_subset.database` and `database_subset.table` parameters into `database_subset.strategy_options`. Then, they will be optional depending on the subset strategy taken.
