### ISSUE TITLE
Using local datastore

### ISSUE THREAD

**Issue by mkalioby** [Qovery/Replibyte#83]
Can I use the datastore on the local disk?rather than the cloud as we host our services onPerm and we don't have S3 complaint service.

**Comment by fabriceclementz** [comment]
I can work on it, I need this feature too.

I suggest this config:

```yaml
datastore:
  local_fs:
    dir: ./data/replibyte # the directory in which the dumps and manifest are stored
```

WDYT @evoxmusic ?
