### ISSUE TITLE
Improve documentation for Google Cloud Storage

### ISSUE THREAD

**Issue by wtait1-ff** [Qovery/Replibyte#89]
Hi team, I'm evaluating using `replibyte` for our GCP environments. This tool looks great! And about a week ago I had read a table of supported datastore providers in the README that included Google Cloud Storage, as GCS is also able to "speak" in the S3 wire protocol.

However it seems all the documentation from the README has been moved to https://www.replibyte.com, but that table of supported datastores was not moved over (having a dedicated docs page on `Datastores` would be helpful).

Also, the datastore config seems to be pretty AWS-centric with keys like `access_key_id`. This would probably be a separate issue but it would also be nice to abstract the datastore configuration to be more provider-agnostic. Either that or, have an additional config layer to namespace the provider-specific keys like

```yaml
datastore:
  aws:
    bucket: my-replibyte-dumps
    region: us-east-2
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
```

---

P.S.

I filed [another issue](https://github.com/Qovery/replibyte/issues/88) about creating issue / PR templates for the repo to aid future users / contributors in authoring requests.
