### ISSUE TITLE
BucketAlreadyOwnedByYou s3

### ISSUE THREAD

**Issue by rileyrohloff** [Qovery/Replibyte#95]
There seems to be something doing on the with s3 part of the tool. After I initially create a dump, which looks like it creates the s3 bucket as well. Every replibyte command after replibyte -c conf.yaml dump create results in [2022-05-10T02:06:58Z ERROR replibyte::datastore::s3] BucketAlreadyOwnedByYou: Your previous request to create the named bucket succeeded and you already own it. My conf.yaml is attached

I am using minio: https://min.io/product/s3-compatibility as my data store.

Thank you in advance for your guidance.

conf.yaml:

```yaml


        source:
          connection_uri: postgres://postgres:*****@dev-pg.rqdev.net:5432/mydatabase
          transformers:
            - database: mydatabase
              table: pending_ticket_messages
              columns:
                - name: message
                  transformer_name: random
        datastore:
          aws:
            bucket: rigs-database-state
            region: us-east-1
            access_key_id: greymatter
            secret_access_key: greymatter
            endpoint:
              custom: 'http://localhost:9000'
        destination:
          connection_uri: postgres://greymatter:******@localhost:5432/redarrow
  
  ```
